name: marschpad
description: Marschpad - Dirigent + Musiker Apps
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  path_provider: ^2.0.12
  http: ^0.13.6
  web_socket_channel: ^2.2.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
